producto = [
    {
        "codigo_producto": "11679",
        "nombre": "Sierra de Poda 400MM",
        "gama": "Herramientas",
        "dimensiones": "0,258",
        "proveedor": "HiperGarden Tools",
        "descripcion": "Gracias a la poda se consigue manipular un poco la naturaleza, dándole la forma que más nos guste. Este trabajo básico de jardinería también facilita que las plantas crezcan de un modo más equilibrado, y que las flores y los frutos vuelvan cada año con regularidad. Lo mejor es dar forma cuando los ejemplares son jóvenes, de modo que exijan pocos cuidados cuando sean adultos. Además de saber cuándo y cómo hay que podar, tener unas herramientas adecuadas para esta labor es también de vital importancia.",
        "cantidad_en_stock": 15,
        "precio_venta": 14,
        "precio_proveedor": 11
    },
    {
        "codigo_producto": "21636",
        "nombre": "Pala",
        "gama": "Herramientas",
        "dimensiones": "0,156",
        "proveedor": "HiperGarden Tools",
        "descripcion": "Palas de acero con cresta de corte en la punta para cortar bien el terreno. Buena penetración en tierras muy compactas.",
        "cantidad_en_stock": 15,
        "precio_venta": 14,
        "precio_proveedor": 13
    },
    {
        "codigo_producto": "22225",
        "nombre": "Rastrillo de Jardín",
        "gama": "Herramientas",
        "dimensiones": "1,064",
        "proveedor": "HiperGarden Tools",
        "descripcion": "Fabuloso rastrillo que le ayudará a eliminar piedras, hojas, ramas y otros elementos incómodos en su jardín.",
        "cantidad_en_stock": 15,
        "precio_venta": 12,
        "precio_proveedor": 11
    },
    {
        "codigo_producto": "30310",
        "nombre": "Azadón",
        "gama": "Herramientas",
        "dimensiones": "0,168",
        "proveedor": "HiperGarden Tools",
        "descripcion": "Longitud:24cm. Herramienta fabricada en acero y pintura epoxi, alargando su durabilidad y preveniendo la corrosión. Diseño pensado para el ahorro de trabajo.",
        "cantidad_en_stock": 15,
        "precio_venta": 12,
        "precio_proveedor": 11
    },
    {
        "codigo_producto": "AR-001",
        "nombre": "Ajedrea",
        "gama": "Aromáticas",
        "dimensiones": "15-20",
        "proveedor": "Murcia Seasons",
        "descripcion": "Planta aromática que fresca se utiliza para condimentar carnes y ensaladas, y seca, para pastas, sopas y guisantes",
        "cantidad_en_stock": 140,
        "precio_venta": 1,
        "precio_proveedor": 0
    },
    {
        "codigo_producto": "AR-002",
        "nombre": "Lavándula Dentata",
        "gama": "Aromáticas",
        "dimensiones": "15-20",
        "proveedor": "Murcia Seasons",
        "descripcion": "Espliego de jardín, Alhucema rizada, Alhucema dentada, Cantueso rizado. Familia: Lamiaceae.Origen: España y Portugal. Mata de unos 60 cm de alto. Las hojas son aromáticas, dentadas y de color verde grisáceas.  Produce compactas espigas de flores pequeñas, ligeramente aromáticas, tubulares,de color azulado y con brácteas púrpuras.  Frutos: nuececillas alargadas encerradas en el tubo del cáliz.  Se utiliza en jardinería y no en perfumería como otros cantuesos, espliegos y lavandas.  Tiene propiedades aromatizantes y calmantes. Adecuadas para la formación de setos bajos. Se dice que su aroma ahuyenta pulgones y otros insectos perjudiciales para las plantas vecinas.",
        "cantidad_en_stock": 140,
        "precio_venta": 1,
        "precio_proveedor": 0
    },
    {
        "codigo_producto": "AR-003",
        "nombre": "Mejorana",
        "gama": "Aromáticas",
        "dimensiones": "15-20",
        "proveedor": "Murcia Seasons",
        "descripcion": "Origanum majorana. No hay que confundirlo con el orégano. Su sabor se parece más al tomillo, pero es más dulce y aromático.Se usan las hojas frescas o secas, picadas, machacadas o en polvo, en sopas, rellenos, quiches y tartas, tortillas, platos con papas y, como aderezo, en ramilletes de hierbas.El sabor delicado de la mejorana se elimina durante la cocción, de manera que es mejor agregarla cuando el plato esté en su punto o en aquéllos que apenas necesitan cocción.",
        "cantidad_en_stock": 140,
        "precio_venta": 1,
        "precio_proveedor": 0
    },
    {
        "codigo_producto": "AR-004",
        "nombre": "Melissa ",
        "gama": "Aromáticas",
        "dimensiones": "15-20",
        "proveedor": "Murcia Seasons",
        "descripcion": "Es una planta perenne (dura varios años) conocida por el agradable y característico olor a limón que desprenden en verano. Nunca debe faltar en la huerta o jardín por su agradable aroma y por los variados usos que tiene: planta olorosa, condimentaria y medicinal. Su cultivo es muy fácil. Le va bien un suelo ligero, con buen drenaje y riego sin exceso. A pleno sol o por lo menos 5 horas de sol por día. Cada año, su abonado mineral correspondiente.En otoño, la melisa pierde el agradable olor a limón que desprende en verano sus flores azules y blancas. En este momento se debe cortar a unos 20 cm. del suelo. Brotará de forma densa en primavera.",
        "cantidad_en_stock": 140,
        "precio_venta": 1,
        "precio_proveedor": 0
    },
    {
        "codigo_producto": "AR-005",
        "nombre": "Mentha Sativa",
        "gama": "Aromáticas",
        "dimensiones": "15-20",
        "proveedor": "Murcia Seasons",
        "descripcion": "¿Quién no conoce la Hierbabuena? Se trata de una plantita muy aromática, agradable y cultivada extensamente por toda España. Es hierba perenne (por tanto vive varios años, no es anual). Puedes cultivarla en maceta o plantarla en la tierra del jardín o en un rincón del huerto. Lo más importante es que cuente con bastante agua. En primavera debes aportar fertilizantes minerales. Vive mejor en semisombra que a pleno sol.Si ves orugas o los agujeros en hojas consecuencia de su ataque, retíralas una a una a mano; no uses insecticidas químicos.",
        "cantidad_en_stock": 140,
        "precio_venta": 1,
        "precio_proveedor": 0
    },
    {
        "codigo_producto": "AR-006",
        "nombre": "Petrosilium Hortense (Peregil)",
        "gama": "Aromáticas",
        "dimensiones": "15-20",
        "proveedor": "Murcia Seasons",
        "descripcion": "Nombre científico o latino: Petroselinum hortense, Petroselinum crispum. Nombre común o vulgar: Perejil, Perejil rizado Familia: Umbelliferae (Umbelíferas). Origen: el origen del perejil se encuentra en el Mediterraneo. Esta naturalizada en casi toda Europa. Se utiliza como condimento y para adorno, pero también en ensaladas. Se suele regalar en las fruterías y verdulerías.El perejil lo hay de 2 tipos: de hojas planas y de hojas rizadas.",
        "cantidad_en_stock": 140,
        "precio_venta": 1,
        "precio_proveedor": 0
    },
    {
        "codigo_producto": "AR-007",
        "nombre": "Salvia Mix",
        "gama": "Aromáticas",
        "dimensiones": "15-20",
        "proveedor": "Murcia Seasons",
        "descripcion": "La Salvia es un pequeño arbusto que llega hasta el metro de alto.Tiene una vida breve, de unos pocos años.En el jardín, como otras aromáticas, queda muy bien en una rocalla o para hacer una bordura perfumada a cada lado de un camino de Salvia. Abona después de cada corte y recorta el arbusto una vez pase la floración.",
        "cantidad_en_stock": 140,
        "precio_venta": 1,
        "precio_proveedor": 0
    },
    {
        "codigo_producto": "AR-008",
        "nombre": "Thymus Citriodra (Tomillo limón)",
        "gama": "Aromáticas",
        "dimensiones": "15-20",
        "proveedor": "Murcia Seasons",
        "descripcion": "Nombre común o vulgar: Tomillo, Tremoncillo Familia: Labiatae (Labiadas).Origen: Región mediterránea.Arbustillo bajo, de 15 a 40 cm de altura. Las hojas son muy pequeñas, de unos 6 mm de longitud; según la variedad pueden ser verdes, verdes grisáceas, amarillas, o jaspeadas. Las flores aparecen de mediados de primavera hasta bien entrada la época estival y se presentan en racimos terminales que habitualmente son de color violeta o púrpura aunque también pueden ser blancas. Esta planta despide un intenso y típico aroma, que se incrementa con el roce. El tomillo resulta de gran belleza cuando está en flor. El tomillo atrae a avispas y abejas. En jardinería se usa como manchas, para hacer borduras, para aromatizar el ambiente, llenar huecos, cubrir rocas, para jardines en miniatura, etc. Arranque las flores y hojas secas del tallo y añádalos a un popurrí, introdúzcalos en saquitos de hierbas o en la almohada.También puede usar las ramas secas con flores para añadir aroma y textura a cestos abiertos.",
        "cantidad_en_stock": 140,
        "precio_venta": 1,
        "precio_proveedor": 0
    },
    {
        "codigo_producto": "AR-009",
        "nombre": "Thymus Vulgaris",
        "gama": "Aromáticas",
        "dimensiones": "15-20",
        "proveedor": "Murcia Seasons",
        "descripcion": "Nombre común o vulgar: Tomillo, Tremoncillo Familia: Labiatae (Labiadas). Origen: Región mediterránea. Arbustillo bajo, de 15 a 40 cm de altura. Las hojas son muy pequeñas, de unos 6 mm de longitud; según la variedad pueden ser verdes, verdes grisáceas, amarillas, o jaspeadas. Las flores aparecen de mediados de primavera hasta bien entrada la época estival y se presentan en racimos terminales que habitualmente son de color violeta o púrpura aunque también pueden ser blancas. Esta planta despide un intenso y típico aroma, que se incrementa con el roce. El tomillo resulta de gran belleza cuando está en flor. El tomillo atrae a avispas y abejas.\r\n En jardinería se usa como manchas, para hacer borduras, para aromatizar el ambiente, llenar huecos, cubrir rocas, para jardines en miniatura, etc. Arranque las flores y hojas secas del tallo y añádalos a un popurrí, introdúzcalos en saquitos de hierbas o en la almohada. También puede usar las ramas secas con flores para añadir aroma y textura a cestos abiertos.",
        "cantidad_en_stock": 140,
        "precio_venta": 1,
        "precio_proveedor": 0
    },
    {
        "codigo_producto": "AR-010",
        "nombre": "Santolina Chamaecyparys",
        "gama": "Aromáticas",
        "dimensiones": "15-20",
        "proveedor": "Murcia Seasons",
        "descripcion": "",
        "cantidad_en_stock": 140,
        "precio_venta": 1,
        "precio_proveedor": 0
    },
    {
        "codigo_producto": "FR-1",
        "nombre": "Expositor Cítricos Mix",
        "gama": "Frutales",
        "dimensiones": "100-120",
        "proveedor": "Frutales Talavera S.A",
        "descripcion": "",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-10",
        "nombre": "Limonero 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El limonero, pertenece al grupo de los cítricos, teniendo su origen hace unos 20 millones de años en el sudeste asiático. Fue introducido por los árabes en el área mediterránea entre los años 1.000 a 1.200, habiendo experimentando numerosas modificaciones debidas tanto a la selección natural mediante hibridaciones espontáneas como a las producidas por el hombre, en este caso buscando las necesidades del mercado.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-100",
        "nombre": "Nectarina",
        "gama": "Frutales",
        "dimensiones": "8/10",
        "proveedor": "Frutales Talavera S.A",
        "descripcion": "Se trata de un árbol derivado por mutación de los melocotoneros comunes, y los únicos caracteres diferenciales son la ausencia de tomentosidad en la piel del fruto. La planta, si se deja crecer libremente, adopta un porte globoso con unas dimensiones medias de 4-6 metros",
        "cantidad_en_stock": 50,
        "precio_venta": 11,
        "precio_proveedor": 8
    },
    {
        "codigo_producto": "FR-101",
        "nombre": "Nogal",
        "gama": "Frutales",
        "dimensiones": "8/10",
        "proveedor": "Frutales Talavera S.A",
        "descripcion": "",
        "cantidad_en_stock": 50,
        "precio_venta": 13,
        "precio_proveedor": 10
    },
    {
        "codigo_producto": "FR-102",
        "nombre": "Olea-Olivos",
        "gama": "Frutales",
        "dimensiones": "8/10",
        "proveedor": "Frutales Talavera S.A",
        "descripcion": "Existen dos hipótesis sobre el origen del olivo, una que postula que proviene de las costas de Siria, Líbano e Israel y otra que considera que lo considera originario de Asia menor. La llegada a Europa probablemente tuvo lugar de mano de los Fenicios, en transito por Chipre, Creta, e Islas del Mar Egeo, pasando a Grecia y más tarde a Italia. Los primeros indicios de la presencia del olivo en las costas mediterráneas españolas coinciden con el dominio romano, aunque fueron posteriormente los árabes los que impulsaron su cultivo en Andalucía, convirtiendo a España en el primer país productor de aceite de oliva a nivel mundial.",
        "cantidad_en_stock": 50,
        "precio_venta": 18,
        "precio_proveedor": 14
    },
    {
        "codigo_producto": "FR-103",
        "nombre": "Olea-Olivos",
        "gama": "Frutales",
        "dimensiones": "10/12",
        "proveedor": "Frutales Talavera S.A",
        "descripcion": "Existen dos hipótesis sobre el origen del olivo, una que postula que proviene de las costas de Siria, Líbano e Israel y otra que considera que lo considera originario de Asia menor. La llegada a Europa probablemente tuvo lugar de mano de los Fenicios, en transito por Chipre, Creta, e Islas del Mar Egeo, pasando a Grecia y más tarde a Italia. Los primeros indicios de la presencia del olivo en las costas mediterráneas españolas coinciden con el dominio romano, aunque fueron posteriormente los árabes los que impulsaron su cultivo en Andalucía, convirtiendo a España en el primer país productor de aceite de oliva a nivel mundial.",
        "cantidad_en_stock": 50,
        "precio_venta": 25,
        "precio_proveedor": 20
    },
    {
        "codigo_producto": "FR-104",
        "nombre": "Olivo de Pica",
        "gama": "Frutales",
        "dimensiones": "10/12",
        "proveedor": "Frutales Talavera S.A",
        "descripcion": "Los olivos de Pica crecen en forma de mata arbustiva con ramas gruesas y flexibles. Este arbusto posee hojas pequeñas de color verde grisáceo por el envés y verde oliva en el haz, en general, estás son angostas, cortas, aserradas y casi puntiagudas. Sus flores son blancas con el centro amarillo, brotan a fines de primavera o principios de verano. Además, al madurar, el olivo de Pica da pequeños frutos llamados aceitunas.",
        "cantidad_en_stock": 50,
        "precio_venta": 20,
        "precio_proveedor": 16
    },
    {
        "codigo_producto": "FR-105",
        "nombre": "Olivo Hojiblanco",
        "gama": "Frutales",
        "dimensiones": "10/12",
        "proveedor": "Frutales Talavera S.A",
        "descripcion": "Olivo de tamaño grande, muy rústico y resistente, se cultiva tanto por sus frutos para la obtención de aceite, como por su gran valor ornamental, ya que encaja perfectamente en jardines de tamaño mediano a grande, y puede dar lugar a espectaculares ejemplares con el paso de los años.",
        "cantidad_en_stock": 50,
        "precio_venta": 20,
        "precio_proveedor": 16
    },
    {
        "codigo_producto": "FR-106",
        "nombre": "Olivo Manzanillo",
        "gama": "Frutales",
        "dimensiones": "10/12",
        "proveedor": "Frutales Talavera S.A",
        "descripcion": "El olivo Manzanillo es una variedad de olivo muy conocida en el mundo. Aunque su origen exacto es incierto, se cree que proviene de España o de algún país mediterráneo como Grecia. Es una variedad muy utilizada en la producción de aceitunas para mesa, por lo que también es conocido como olivo de mesa.",
        "cantidad_en_stock": 50,
        "precio_venta": 20,
        "precio_proveedor": 16
    },
    {
        "codigo_producto": "FR-107",
        "nombre": "Peral",
        "gama": "Frutales",
        "dimensiones": "8/10",
        "proveedor": "Frutales Talavera S.A",
        "descripcion": "",
        "cantidad_en_stock": 50,
        "precio_venta": 10,
        "precio_proveedor": 8
    },
    {
        "codigo_producto": "FR-108",
        "nombre": "Prunus Cerasifera",
        "gama": "Frutales",
        "dimensiones": "10/12",
        "proveedor": "Frutales Talavera S.A",
        "descripcion": "Prunus cerasifera es un árbol caducifolio, de hoja caduca y crecimiento rápido que puede alcanzar los 12 metros de altura. En algunas zonas de Europa, el árbol es un árbol ornamental popular, y varias formas hortícolas están disponibles, como las variedades de hojas purpúreas o de hojas doradas.",
        "cantidad_en_stock": 50,
        "precio_venta": 25,
        "precio_proveedor": 20
    },
    {
        "codigo_producto": "FR-109",
        "nombre": "Prunus Cerasifera",
        "gama": "Frutales",
        "dimensiones": "8/10",
        "proveedor": "Frutales Talavera S.A",
        "descripcion": "Prunus cerasifera es un árbol caducifolio, de hoja caduca y crecimiento rápido que puede alcanzar los 12 metros de altura. En algunas zonas de Europa, el árbol es un árbol ornamental popular, y varias formas hortícolas están disponibles, como las variedades de hojas purpúreas o de hojas doradas.",
        "cantidad_en_stock": 50,
        "precio_venta": 18,
        "precio_proveedor": 14
    },
    {
        "codigo_producto": "FR-11",
        "nombre": "Mandarino 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El mandarino es un árbol frutal híbrido, que pertenece a la familia de las Rutaceae, subfamilia Aurantoideae, género Citrus, especie Citrus reticulata. El mandarino se cree que es originario del sudeste asiático, desde donde se expandió al resto de Asia, pasando por Europa y finalmente América. Los mandarinos tienen un porte más pequeño que el de los naranjos y producen frutas de menor tamaño. Sus hojas son más pequeñas y estrechas que las de los naranjos y suelen ser de un color verde más oscuro. Sus frutas son de color naranja intenso y son más fáciles de pelar que las naranjas, además de tener un sabor más dulce y una menor cantidad de semillas.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-12",
        "nombre": "Manzano 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El manzano es un árbol frutal de la familia de las Rosáceas que puede llegar a medir hasta 10 metros de altura. Es originario de Europa, Asia y África del Norte. Produce una fruta conocida como manzana, que puede tener diferentes formas y colores, como rojo, verde o amarillo. La manzana es una fruta muy popular y versátil en la cocina, ya que se puede comer cruda, cocida, en compotas, jugos y postres.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-13",
        "nombre": "Membrillo 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El membrillo es un árbol frutal que pertenece a la familia de las Rosáceas. Es originario de Asia Menor y Oriente Próximo, aunque se ha extendido por otras regiones del mundo con climas mediterráneos. Produce una fruta llamada membrillo, la cual es de forma similar a una pera, con una piel amarilla brillante y una carne dura y astringente. Esta fruta se suele utilizar para hacer dulces y jaleas.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-14",
        "nombre": "Membrillo 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El membrillo es un árbol frutal que pertenece a la familia de las Rosáceas. Es originario de Asia Menor y Oriente Próximo, aunque se ha extendido por otras regiones del mundo con climas mediterráneos. Produce una fruta llamada membrillo, la cual es de forma similar a una pera, con una piel amarilla brillante y una carne dura y astringente. Esta fruta se suele utilizar para hacer dulces y jaleas.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-15",
        "nombre": "Mespino 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El espino o mezclino es un árbol frutal que pertenece a la familia de las Rosáceas. Es originario de Europa y Asia. Produce una fruta llamada espino o mezclino, la cual es similar a una pequeña manzana o pera con una piel de color amarillo o naranja y una carne dura y ácida. Esta fruta se suele utilizar para hacer dulces, mermeladas y jaleas.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-16",
        "nombre": "Mezclino 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El espino o mezclino es un árbol frutal que pertenece a la familia de las Rosáceas. Es originario de Europa y Asia. Produce una fruta llamada espino o mezclino, la cual es similar a una pequeña manzana o pera con una piel de color amarillo o naranja y una carne dura y ácida. Esta fruta se suele utilizar para hacer dulces, mermeladas y jaleas.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-17",
        "nombre": "Melocotonero 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El melocotonero es un árbol frutal que pertenece a la familia de las Rosáceas. Es originario de China y ha sido cultivado desde la antigüedad en Asia y Europa. Produce una fruta conocida como melocotón, la cual tiene una piel aterciopelada de colores que varían entre amarillo, rojo y naranja, y una carne jugosa y dulce. Los melocotones se pueden consumir crudos, en conserva, en mermeladas o en jugos.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-18",
        "nombre": "Manzano 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El manzano es un árbol frutal de la familia de las Rosáceas que puede llegar a medir hasta 10 metros de altura. Es originario de Europa, Asia y África del Norte. Produce una fruta conocida como manzana, que puede tener diferentes formas y colores, como rojo, verde o amarillo. La manzana es una fruta muy popular y versátil en la cocina, ya que se puede comer cruda, cocida, en compotas, jugos y postres.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-19",
        "nombre": "Granado 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El granado es un árbol frutal que pertenece a la familia de las Lythraceae. Es originario de Asia y se ha cultivado desde la antigüedad en diversas regiones del mundo con climas mediterráneos. Produce una fruta conocida como granada, la cual tiene una corteza dura de color rojo o amarillo, y en su interior una serie de semillas recubiertas de una pulpa roja y jugosa. Las granadas se consumen frescas, en jugos, en postres o en la preparación de salsas y ensaladas.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-2",
        "nombre": "Naranjo 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El naranjo es un árbol frutal cítrico que pertenece a la familia de las Rutáceas. Es originario de China, aunque se ha extendido por diversas regiones del mundo con climas mediterráneos. Produce una fruta conocida como naranja, la cual tiene una corteza gruesa y rugosa de color naranja brillante, y en su interior una pulpa jugosa y dulce. Las naranjas se consumen frescas, en jugos, en postres y en la preparación de salsas y mermeladas.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-20",
        "nombre": "Granado 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El granado es un árbol frutal que pertenece a la familia de las Lythraceae. Es originario de Asia y se ha cultivado desde la antigüedad en diversas regiones del mundo con climas mediterráneos. Produce una fruta conocida como granada, la cual tiene una corteza dura de color rojo o amarillo, y en su interior una serie de semillas recubiertas de una pulpa roja y jugosa. Las granadas se consumen frescas, en jugos, en postres o en la preparación de salsas y ensaladas.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-21",
        "nombre": "Higuera 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "La higuera es un árbol frutal que pertenece a la familia de las Moráceas. Es originaria de Asia Occidental y se ha extendido por las regiones mediterráneas y otras zonas con climas cálidos. Produce una fruta conocida como higo, la cual tiene una forma similar a una pera, con una piel delgada de color verde o morado y una carne dulce y jugosa. Los higos se consumen frescos, secos o en la elaboración de dulces y mermeladas.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-22",
        "nombre": "Higueron 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "La higuera es un árbol frutal que pertenece a la familia de las Moráceas. Es originaria de Asia Occidental y se ha extendido por las regiones mediterráneas y otras zonas con climas cálidos. Produce una fruta conocida como higo, la cual tiene una forma similar a una pera, con una piel delgada de color verde o morado y una carne dulce y jugosa. Los higos se consumen frescos, secos o en la elaboración de dulces y mermeladas.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-23",
        "nombre": "Almendro 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El almendro es un árbol frutal que pertenece a la familia de las Rosáceas. Es originario del Medio Oriente y ha sido cultivado desde tiempos antiguos en las regiones mediterráneas. Produce una semilla conocida como almendra, la cual está contenida en una cáscara dura y se utiliza para hacer aceite, dulces y en la cocina como ingrediente.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-24",
        "nombre": "Almendro 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El almendro es un árbol frutal que pertenece a la familia de las Rosáceas. Es originario del Medio Oriente y ha sido cultivado desde tiempos antiguos en las regiones mediterráneas. Produce una semilla conocida como almendra, la cual está contenida en una cáscara dura y se utiliza para hacer aceite, dulces y en la cocina como ingrediente.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-25",
        "nombre": "Avellano 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El avellano es un árbol frutal que pertenece a la familia de las Betuláceas. Es originario de Europa y Asia Menor, aunque también se encuentra en otras regiones del mundo. Produce una semilla conocida como avellana, la cual está contenida en una cáscara dura y se utiliza como fruto seco o en la elaboración de dulces y postres.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-26",
        "nombre": "Avellano 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El avellano es un árbol frutal que pertenece a la familia de las Betuláceas. Es originario de Europa y Asia Menor, aunque también se encuentra en otras regiones del mundo. Produce una semilla conocida como avellana, la cual está contenida en una cáscara dura y se utiliza como fruto seco o en la elaboración de dulces y postres.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-27",
        "nombre": "Castano 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El castaño es un árbol frutal que pertenece a la familia de las Fagáceas. Es originario de Asia y Europa y ha sido cultivado desde tiempos antiguos por sus frutos y su madera. Produce una semilla conocida como castaña, la cual está contenida en una cáscara espinosa y se consume cruda, asada o en la elaboración de dulces y postres.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-28",
        "nombre": "Castano 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El castaño es un árbol frutal que pertenece a la familia de las Fagáceas. Es originario de Asia y Europa y ha sido cultivado desde tiempos antiguos por sus frutos y su madera. Produce una semilla conocida como castaña, la cual está contenida en una cáscara espinosa y se consume cruda, asada o en la elaboración de dulces y postres.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-29",
        "nombre": "Pistacho 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El pistacho es un árbol frutal que pertenece a la familia de las Anacardiáceas. Es originario de Asia Central y ha sido cultivado desde tiempos antiguos en las regiones del Mediterráneo y Asia. Produce una semilla conocida como pistacho, la cual está contenida en una cáscara dura y se consume como fruto seco o en la elaboración de dulces y postres.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-3",
        "nombre": "Naranjo 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El naranjo es un árbol frutal cítrico que pertenece a la familia de las Rutáceas. Es originario de China, aunque se ha extendido por diversas regiones del mundo con climas mediterráneos. Produce una fruta conocida como naranja, la cual tiene una corteza gruesa y rugosa de color naranja brillante, y en su interior una pulpa jugosa y dulce. Las naranjas se consumen frescas, en jugos, en postres y en la preparación de salsas y mermeladas.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-30",
        "nombre": "Pistacho 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El pistacho es un árbol frutal que pertenece a la familia de las Anacardiáceas. Es originario de Asia Central y ha sido cultivado desde tiempos antiguos en las regiones del Mediterráneo y Asia. Produce una semilla conocida como pistacho, la cual está contenida en una cáscara dura y se consume como fruto seco o en la elaboración de dulces y postres.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-31",
        "nombre": "Mandarino 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El mandarino es un árbol frutal híbrido, que pertenece a la familia de las Rutaceae, subfamilia Aurantoideae, género Citrus, especie Citrus reticulata. El mandarino se cree que es originario del sudeste asiático, desde donde se expandió al resto de Asia, pasando por Europa y finalmente América. Los mandarinos tienen un porte más pequeño que el de los naranjos y producen frutas de menor tamaño. Sus hojas son más pequeñas y estrechas que las de los naranjos y suelen ser de un color verde más oscuro. Sus frutas son de color naranja intenso y son más fáciles de pelar que las naranjas, además de tener un sabor más dulce y una menor cantidad de semillas.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-32",
        "nombre": "Peral 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El peral es un árbol frutal que pertenece a la familia de las Rosáceas. Es originario de Europa y Asia y ha sido cultivado desde tiempos antiguos en diversas regiones del mundo. Produce una fruta conocida como pera, la cual puede tener diferentes formas, tamaños y colores, como verde, amarillo o rojo. Las peras se consumen frescas, en compotas, en postres, en jugos y en la preparación de salsas.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-33",
        "nombre": "Olivo Hojiblanco 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "Olivo de tamaño grande, muy rústico y resistente, se cultiva tanto por sus frutos para la obtención de aceite, como por su gran valor ornamental, ya que encaja perfectamente en jardines de tamaño mediano a grande, y puede dar lugar a espectaculares ejemplares con el paso de los años.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-34",
        "nombre": "Olivo Hojiblanco 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "Olivo de tamaño grande, muy rústico y resistente, se cultiva tanto por sus frutos para la obtención de aceite, como por su gran valor ornamental, ya que encaja perfectamente en jardines de tamaño mediano a grande, y puede dar lugar a espectaculares ejemplares con el paso de los años.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-35",
        "nombre": "Olivo Picual 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "Olivo de tamaño grande, muy rústico y resistente, se cultiva tanto por sus frutos para la obtención de aceite, como por su gran valor ornamental, ya que encaja perfectamente en jardines de tamaño mediano a grande, y puede dar lugar a espectaculares ejemplares con el paso de los años.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-36",
        "nombre": "Olivo Picual 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "Olivo de tamaño grande, muy rústico y resistente, se cultiva tanto por sus frutos para la obtención de aceite, como por su gran valor ornamental, ya que encaja perfectamente en jardines de tamaño mediano a grande, y puede dar lugar a espectaculares ejemplares con el paso de los años.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-37",
        "nombre": "Kiwi 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El kiwi es una planta trepadora de la familia Actinidiaceae, género Actinidia. Es originario de Asia, específicamente de China. Su fruta es conocida también como kiwi, la cual tiene una piel marrón y peluda, y una pulpa verde con pequeñas semillas comestibles. El kiwi es una fuente excelente de vitamina C y otras vitaminas y minerales. Se consume fresco, en postres, ensaladas y jugos.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-38",
        "nombre": "Kiwi 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El kiwi es una planta trepadora de la familia Actinidiaceae, género Actinidia. Es originario de Asia, específicamente de China. Su fruta es conocida también como kiwi, la cual tiene una piel marrón y peluda, y una pulpa verde con pequeñas semillas comestibles. El kiwi es una fuente excelente de vitamina C y otras vitaminas y minerales. Se consume fresco, en postres, ensaladas y jugos.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-39",
        "nombre": "Chirimoyo 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "La chirimoya es un árbol frutal de la familia de las Annonaceae. Es originaria de América del Sur, específicamente de la región andina. Produce una fruta conocida como chirimoya, la cual tiene una piel verde con escamas y una pulpa blanca y dulce, con numerosas semillas en su interior. La chirimoya se consume fresca o en la preparación de postres y batidos.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-4",
        "nombre": "Limón 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El limonero es un árbol frutal cítrico de la familia de las Rutáceas. Es originario de Asia, específicamente de India, pero se ha extendido por todo el mundo con climas cálidos y templados. Produce una fruta conocida como limón, la cual tiene una cáscara amarilla y una pulpa ácida y jugosa. Los limones se utilizan en la cocina para dar sabor a platos, bebidas y postres, así como para hacer limonada y otros jugos.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-40",
        "nombre": "Chirimoyo 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "La chirimoya es un árbol frutal de la familia de las Annonaceae. Es originaria de América del Sur, específicamente de la región andina. Produce una fruta conocida como chirimoya, la cual tiene una piel verde con escamas y una pulpa blanca y dulce, con numerosas semillas en su interior. La chirimoya se consume fresca o en la preparación de postres y batidos.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-41",
        "nombre": "Aguacate 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El aguacate es un árbol frutal de la familia de las Lauráceas, género Persea, especie Persea americana. El aguacate es originario de Mesoamérica, desde donde se expandió a otras partes del mundo. El aguacate es una fruta muy rica en nutrientes, contiene grasas saludables, vitaminas y minerales. La variedad más común de aguacate tiene una piel verde y una pulpa amarilla o verde, cremosa y suave. El aguacate se consume principalmente fresco, en ensaladas, guacamole, y en la preparación de salsas.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-42",
        "nombre": "Aguacate 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El aguacate es un árbol frutal de la familia de las Lauráceas, género Persea, especie Persea americana. El aguacate es originario de Mesoamérica, desde donde se expandió a otras partes del mundo. El aguacate es una fruta muy rica en nutrientes, contiene grasas saludables, vitaminas y minerales. La variedad más común de aguacate tiene una piel verde y una pulpa amarilla o verde, cremosa y suave. El aguacate se consume principalmente fresco, en ensaladas, guacamole, y en la preparación de salsas.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-43",
        "nombre": "Membrillo 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El membrillo es un árbol frutal de la familia de las Rosáceas, género Cydonia, especie Cydonia oblonga. El membrillo es originario de la región del Cáucaso, aunque también se ha cultivado en la región mediterránea desde la antigüedad. El membrillo produce una fruta grande y amarilla, conocida también como membrillo, la cual es dura y áspera en su exterior, con una pulpa firme y aromática. El membrillo se consume en dulces, mermeladas y jaleas, además de usarse en la preparación de algunos platos de carne.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-44",
        "nombre": "Membrillo 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El membrillo es un árbol frutal de la familia de las Rosáceas, género Cydonia, especie Cydonia oblonga. El membrillo es originario de la región del Cáucaso, aunque también se ha cultivado en la región mediterránea desde la antigüedad. El membrillo produce una fruta grande y amarilla, conocida también como membrillo, la cual es dura y áspera en su exterior, con una pulpa firme y aromática. El membrillo se consume en dulces, mermeladas y jaleas, además de usarse en la preparación de algunos platos de carne.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-45",
        "nombre": "Nectarina 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "La nectarina es una variedad de melocotón que pertenece a la familia de las Rosáceas, género Prunus, especie Prunus persica var. nucipersica. La nectarina se cree que es originaria de China, aunque se ha extendido a otras regiones del mundo. La nectarina produce una fruta similar al melocotón, pero con una piel lisa y brillante, sin vellosidades. Su pulpa es jugosa, de sabor dulce y muy aromática. Las nectarinas se consumen frescas, en postres y en la elaboración de mermeladas.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-46",
        "nombre": "Nectarina 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "La nectarina es una variedad de melocotón que pertenece a la familia de las Rosáceas, género Prunus, especie Prunus persica var. nucipersica. La nectarina se cree que es originaria de China, aunque se ha extendido a otras regiones del mundo. La nectarina produce una fruta similar al melocotón, pero con una piel lisa y brillante, sin vellosidades. Su pulpa es jugosa, de sabor dulce y muy aromática. Las nectarinas se consumen frescas, en postres y en la elaboración de mermeladas.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-47",
        "nombre": "Mango 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El mango es un árbol frutal de la familia de las Anacardiáceas, género Mangifera, especie Mangifera indica. El mango es originario de la India, aunque se ha extendido a otras regiones tropicales y subtropicales del mundo. El mango produce una fruta de forma ovalada y piel lisa, que varía en color según la variedad, pudiendo ser amarilla, naranja, roja o verde. Su pulpa es jugosa, dulce y de sabor exótico. El mango se consume principalmente fresco, en jugos, en postres y en la elaboración de salsas.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    },
    {
        "codigo_producto": "FR-48",
        "nombre": "Mango 1 año injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El mango es un árbol frutal de la familia de las Anacardiáceas, género Mangifera, especie Mangifera indica. El mango es originario de la India, aunque se ha extendido a otras regiones tropicales y subtropicales del mundo. El mango produce una fruta de forma ovalada y piel lisa, que varía en color según la variedad, pudiendo ser amarilla, naranja, roja o verde. Su pulpa es jugosa, dulce y de sabor exótico. El mango se consume principalmente fresco, en jugos, en postres y en la elaboración de salsas.",
        "cantidad_en_stock": 15,
        "precio_venta": 5,
        "precio_proveedor": 3
    },
    {
        "codigo_producto": "FR-49",
        "nombre": "Granado 2 años injerto",
        "gama": "Frutales",
        "dimensiones": "",
        "proveedor": "NaranjasValencianas.com",
        "descripcion": "El granado es un árbol frutal de la familia de las Lythraceae, género Punica, especie Punica granatum. El granado es originario de la región del Cáucaso, aunque también se ha cultivado en el Mediterráneo, en Asia y en América desde tiempos antiguos. El granado produce una fruta conocida como granada, la cual tiene una piel gruesa y dura, de color rojo o amarillo, con numerosas semillas rodeadas de una pulpa roja o rosada, jugosa y de sabor agridulce. La granada se consume fresca, en zumos y en la preparación de salsas y postres.",
        "cantidad_en_stock": 15,
        "precio_venta": 7,
        "precio_proveedor": 5
    }]